language: python
python:
  - "2.7"
#  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
  - "pypy3"
sudo: false
install: true
script:
#  - python setup.py nosetests
  - python setup.py install
  - vcardgen -c 2 -f Kontakt.vcf
  - cat Kontakt.vcf
  - vcardgen
#after_success: coveralls
notifications:
  email:
    - post@davidak.de
